### ISSUE TITLE
What type should I used for "bytes"

### ISSUE THREAD

**Issue by jiak94** [flavray/avro-rs#66]
currently, I am using `Vec<u8>`, but when serialize the data, I get an error of `value does not match schema`

**Comment by jiak94** [comment]
> seems like adding the following code to `types.rs` will solve this problem.... Haven't try it out.
> 
> ```rust
> impl ToAvro for Vec<u8> {
>     fn avro(self) -> Value {
>         Value::Bytes(self)
>     }
> }
> ```

This method actually don't work. Still waiting for solution.

**Comment by flavray** [comment]
Do you have a code snippet causing the serialization issue? 🙂
Serializing a `&[u8]` should give you a `Bytes` object. See [here](https://github.com/flavray/avro-rs/blob/7b820c13a1f25c7fd35850a6fed921aabc3ed103/src/types.rs#L114)

**Comment by jiak94** [comment]
What I've done is:
### Schema
```json
{
    "type": "record",
    "name": "test", 
    "fileds": [
        {
            "name": "item",
            "type": "bytes"
        }
    ]
}
```

### struct
```rust
pub struct Test {
    pub item:Vec<u8>
}
```

### serrialize function
```rust 
pub fn serialize(schema_str: &str, obj: &Test) ->() {
   let schema = Schema::parse_str(schema_str).unwrap();
   let mut writer = Writer::new(&schema, Vec::new());
   
  // error happens here
 match writer.append_str(obj).unwrap();

... some more code
...
}
```
```

**Comment by flavray** [comment]
There was a bug in the resolving process that was preventing `Vec` to be interpreted as `Bytes`. I've released `v0.6.5` with a bugfix.

The way to go for your case should be:

```rust
use avro_rs::{Schema, to_value, Writer};

pub fn serialize(schema_str: &str, obj: &Test) ->() {
   let schema = Schema::parse_str(schema_str).unwrap();
   let mut writer = Writer::new(&schema, Vec::new());

   let value = to_value(obj).resolve(&schema).unwrap();  // this is needed for serialization to match your schema
   
   match writer.append(value).unwrap() {
      ... some more code
   }
}
```

**Comment by gklijs** [comment]
Not sure if this is the correct place, but I ran into trouble serialising to bytes, when the schema contains a fixed value. Instead of a `Value::Fixed` to_value will create a `Value::Array` and the resolve also doesn't fix it, while I think it should. So
```rust
    fn resolve_fixed(self, size: usize) -> Result<Self, Error> {
        match self {
            Value::Fixed(n, bytes) => if n == size {
                Ok(Value::Fixed(n, bytes))
            } else {
                Err(SchemaResolutionError::new(format!(
                    "Fixed size mismatch, {} expected, got {}",
                    size, n
                )).into())
            },
            other => {
                Err(SchemaResolutionError::new(format!("String expected, got {:?}", other)).into())
            },
        }
    }
```
Should also match on `Value::Array` I think. (And the copy/paste in the error should be corrected String -> Fixed)

**Comment by gklijs** [comment]
@flavray 
My solution to properly handle fixed values, as the create an Array of Value::Int currently:
```rust
fn vec_to_fixed(vec: Vec<Value>) -> Result<Value, SRCError> {
    let mut errors: Vec<Value> = vec![];
    let mut hits: Vec<u8> = vec![];
    vec.iter().for_each(|part| match part {
        Value::Int(v) => {
            if *v >= 0 && *v <= 255 {
                hits.push((v & 0xff) as u8)
            } else {
                errors.push(Value::Int(*v))
            }
        }
        other => errors.push(other.clone()),
    });
    if errors.is_empty() {
        Ok(Value::Fixed(vec.len(), hits))
    } else {
        Err(SRCError::non_retryable_from_err(
            format!(
                "Found non-int values and/or ints that can't be converted to bytes: {:#?}",
                errors
            ),
            "could not fix fixed",
        ))
    }
}

    fn fix_fixed_fixed(self, size: usize) -> Result<Self, SRCError> {
        match self {
            Value::Fixed(n, bytes) => {
                if n == size {
                    Ok(Value::Fixed(n, bytes))
                } else {
                    Err(SRCError::non_retryable_from_err(
                        format!("Fixed size mismatch, {} expected, got {}", size, n),
                        "could not fix fixed",
                    ))
                }
            }
            Value::Array(vec) => {
                if vec.len() == size {
                    vec_to_fixed(vec)
                } else {
                    Err(SRCError::non_retryable_from_err(
                        format!("Array size mismatch, {} expected, got {}", size, vec.len()),
                        "could not fix fixed",
                    ))
                }
            }
            other => Err(SRCError::non_retryable_from_err(
                format!("Fixed or vector expected, got {:?}", other),
                "could not fix fixed",
            )),
        }
    }
```
Copied some logic from resolve to make it work transitively.

**Comment by campbellC** [comment]
I'm not sure of all of the ins and outs here but for my use case where I want to use `Vec<u8>` and have this serialized into an avro `bytes` I followed the advice [here](https://github.com/flavray/avro-rs/issues/108) to use the serde_bytes crate. So the following works fine for both serialization and deserialization using `append_ser`:
```rust
    #[test]
    fn avro_serde_list_of_foos() {
        const FOO_SCHEMA: &str = r#"
            {
                "type": "record",
                "name": "Bla",
                "fields": [
                    {"name": "some_bytes", "type": "bytes"}
                ]
            }
            "#;
        #[derive(PartialEq, Eq, Deserialize, Serialize, Debug, Hash, Clone)]
        pub struct Foo {
            #[serde(with = "serde_bytes")]
            pub some_bytes: Vec<u8>,
        }
        let foo_schema = Schema::parse_str(FOO_SCHEMA).unwrap();
        let mut buf = Vec::new();
        let mut writer = Writer::new(&foo_schema, &mut buf);

        let foos = vec![
            Foo {
                some_bytes: vec![4, 5, 6],
            },
            Foo {
                some_bytes: vec![1, 2, 3],
            },
        ];

        for foo in &foos {
            writer.append_ser(foo).unwrap();
        }
        writer.flush().unwrap();

        let reader = Reader::with_schema(&foo_schema, &buf[..]).unwrap();
        let mut deser = Vec::<Foo>::new();
        for value in reader {
            deser.push(from_value(&value.unwrap()).unwrap());
        }
        assert_eq!(foos, deser);
    }
```
